const charOffsets = new Map();
window.CHAR_SELECT_HEAD_OFFSETS = charOffsets;
charOffsets.set("Lea", { x: 4, y: 0 });
charOffsets.set("Shizuka", { x: 3, y: 0 });
charOffsets.set("Shizuka0", { x: 3, y: 0 });
charOffsets.set("Emilie", { x: 3, y: 1 });
charOffsets.set("Sergey", { x: 4, y: 1 });
charOffsets.set("Schneider", { x: 3, y: 0 });
charOffsets.set("Schneider2", { x: 3, y: 0 });
charOffsets.set("Hlin", { x: 3, y: 1 });
charOffsets.set("Grumpy", { x: 2, y: 0 });
charOffsets.set("Glasses", { x: 4, y: 1 });
charOffsets.set("Apollo", { x: 4, y: 1 });
charOffsets.set("Joern", { x: 4, y: 0 });
charOffsets.set("Triblader1", { x: 4, y: 1 });
charOffsets.set("Luke", { x: 3, y: 0 });
